### ISSUE TITLE
Cannot generate link to share

### ISSUE THREAD

**Issue by ParanoikCZE** [trakos/fbpviewer#7]
After clicking the button to share, the website says it failed to create a URL.
![obrazek](https://user-images.githubusercontent.com/19796452/163788156-d2ccda8e-480d-402c-b50f-5c9bc3fb55d4.png)

Note: may be related, are shared links from http://fbpviewer.trakos.pl migrated?

**Comment by trakos** [comment]
Thanks @ParanoikCZE for the report. I've fixed the problem. I was still tweaking the deployment, so it wasn't stable yet.

Unfortunately, I haven't kept the backups from the old site.
